# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180725_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Launch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
