# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_launcher_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
